apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fluentd-cluster-logging.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "fluentd-cluster-logging.name" . }}
    helm.sh/chart: {{ include "fluentd-cluster-logging.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "fluentd-cluster-logging.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "fluentd-cluster-logging.fullname" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "fluentd-cluster-logging.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "fluentd-cluster-logging.fullname" . }}
  namespace: {{ .Release.Namespace }}