{{- if eq .Values.logSink.type "gcp" -}}
{{- if (not .Values.logSink.gcpServiceAccountSecret.enabled) -}}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fluentd-cluster-logging.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "fluentd-cluster-logging.name" . }}
    helm.sh/chart: {{ include "fluentd-cluster-logging.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  application_default_credentials.json: {{ .Values.logSink.gcpServiceAccountJson | b64enc }}
{{- end -}}
{{- end -}}
