apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "ingress.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ingress.name" . }}
    helm.sh/chart: {{ include "ingress.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  hosts:
    {{- toYaml .Values.hosts | nindent 6 }}
  gateways:
    - {{ include "ingress.fullname" . }}-gateway
  http:
  {{- range .Values.services }}
    - match:
      - uri:
          prefix: {{ .prefix }}
      rewrite:
        uri: /
      route:
      - destination:
          port:
            number: {{ .port }}
          host: {{ .name }}
  {{- end }}
