---
- name: Insert path to ros gem
  include_role:
    name: prepd/aliases
  vars:
    type: profile
    aliases_marker: ros
    aliases_block: |
      export RUBYLIB={{ project_dir }}/ros/ros/lib
      eval "$(direnv hook {{ ansible_env.SHELL.split('/') | last }})"

- name: copy ros command
  command: cp {{ project_dir }}/ros/ros/exe/ros /usr/local/bin
  become: yes

- name: Install direnv for environment loading
  apt:
    name: [direnv]
  become: yes
