image:
  repository: mdillon/postgis
  tag: 10
fullnameOverride: postgres
postgresqlDataDir: /data/pgdata
postgresqlDatabase: postgres
postgresqlUsername: admin
postgresqlPassword: admin
persistence:
  enabled: true
  mountPath: /data/
  existingClaim: postgres
securityContext:
  enabled: false
resources: 
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 0.5
    memory: 1.5Gi
