apiVersion: skaffold/v1beta9
kind: Config
deploy:
  helm:
    releases:
      - name: postgres
        chartPath: stable/postgresql
        skipBuildDependencies: true
        valuesFiles:
          - ./helm-values/postgres.yaml
      - name: redis
        chartPath: stable/redis
        skipBuildDependencies: true
        valuesFiles:
          - ./helm-values/redis.yaml
