{{- if .Values.hook.upgradeMigration.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "service.fullname" . }}-migration
  labels:
    app.kubernetes.io/name: {{ include "service.name" . }}
    helm.sh/chart: {{ include "service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        # Disable istio injection until this issue is resolved
        # It then requires istio is deployed with Permissive mode
        # https://github.com/istio/istio/issues/6324
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: {{ .Values.hook.upgradeMigration.restartPolicy }}
      containers:
        - name: {{ include "service.name" . }}-migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: 
            {{- toYaml .Values.hook.upgradeMigration.command | trim | nindent 12 }}
          {{- with .Values.app.env }}
          env:
            {{- range $name, $value := . }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- if or (.Values.app.envFromSecrets) (.Values.app.envFromConfigMaps) }}
          envFrom:
            {{- range .Values.app.envFromConfigMaps }}
            - configMapRef:
                name: {{ . | quote }}
            {{- end }}
            {{- range .Values.app.envFromSecrets }}
            - secretRef:
                name: {{ . | quote }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.hook.upgradeMigration.resources | trim | nindent 12 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | trim | nindent 8}}
      {{- end }}
      {{- if .Values.secretMounts }}
      volumes:
        {{- range $index, $secretMount := .Values.secretMounts }}
        - name: secret-volume-{{ $index }}
          secret:
            secretName: {{ $secretMount.secretName }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
